# Generated by Django 5.1.4 on 2025-02-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_board_board_id_remove_board_user_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('user', 'board_title')},
        ),
    ]
