# Generated by Django 5.1.4 on 2025-02-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_board_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.card'),
        ),
    ]
