# Generated by Django 5.1.4 on 2025-02-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_task_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
