# Generated by Django 5.1.4 on 2025-02-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_task_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
