# Generated by Django 5.1.4 on 2025-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_alter_user_password_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='showNotification',
            field=models.BooleanField(default=False),
        ),
    ]
